# This workflow tests the ModbusSimulator with Bun
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bun CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies (bun)
      run: bun install

    - name: Run unit and integration tests
      run: bun run test:unit && bun run test:integration
      env:
        NODE_ENV: test

    - name: Build release
      run: bun run build

